/* 프로젝트 순서가 사이트 표시 순서입니다. 새 작업은 배열 맨 위에 추가하세요. */
window.PORTFOLIO_PROJECTS = [
  {
    id: "kkumteo",
    title: "꿈터",
    subtitle: "Dream Yard",
    year: "2025",
    date: "2025.07.21",
    award: "제34회 대전디자인어워드 입상",
    tools: ["Midjourney", "Adobe Illustrator"],
    category: "Midjourney / Adobe Illustrator",
    cover: "images/project01/cover.jpg",
    coverPosition: "top",
    coverAlt: "꿈터 프로젝트 포스터 — 대전의 미래형 복합 문화 랜드마크",
    images: ["images/project01/01.jpg?v=2"],
    detailFullBleed: true,
    descriptionKo: "대전을 대표하는 관광지와 도시의 상징성을 새롭게 제안한 가상 도시 랜드마크 프로젝트입니다. 과거 꿈돌이랜드의 장소성과 ‘꿈돌이’라는 지역 상징을 현대적으로 재해석해, 대형 전망대를 중심으로 놀이시설·상업시설·휴식공간·드론 서비스가 결합된 복합 문화공간 ‘꿈터’를 기획했습니다.\n\n관광 활성화와 대전만의 지역 브랜딩을 함께 고려했으며, 미래적인 공간과 친근한 캐릭터 이미지를 결합해 방문 자체가 하나의 경험이 되는 랜드마크를 표현했습니다. Midjourney를 활용해 공간과 비주얼 콘셉트를 시각화했으며, Adobe Illustrator를 통해 전체 그래픽 구성과 레이아웃을 완성했습니다.\n\n본 프로젝트는 제34회 대전디자인어워드에서 입상했습니다.",
    descriptionEn: "Dream Yard is a conceptual urban landmark project created to propose a new tourism destination and visual identity for Daejeon. Inspired by the former Dreamland site and the city’s symbolic character, Kkumdori, the project reimagines the area as a futuristic mixed-use destination combining an observation deck, entertainment facilities, commercial spaces, relaxation areas, and drone-based services.\n\nMidjourney was used to visualize the spatial and visual concepts, while Adobe Illustrator was used to develop the overall graphic composition and presentation layout.\n\nThe project received an Award at the 34th Daejeon Design Award.",
    description: "A conceptual urban landmark project proposing a new tourism destination and visual identity for Daejeon.",
    video: null
  },
  {
    id: "hong-berry",
    title: "‘딸기요정’ 홍베리",
    subtitle: "Hong Berry — Strawberry Fairy Character Design",
    year: "2025",
    date: "2025.12.07",
    participation: "홍성 특산물 캐릭터 공모전 참가작",
    tools: ["Adobe Illustrator", "Adobe Photoshop", "Nano Banana Pro"],
    category: "Character Branding / Visual Identity",
    cover: "images/project02/cover.jpg?v=2",
    coverAlt: "딸기요정 홍베리 캐릭터 대표 이미지",
    images: ["images/project02/01.jpg?v=2"],
    detailWidth: "70%",
    descriptionKo: "‘딸기요정’ 홍베리는 홍성의 특산물을 친근하고 기억하기 쉬운 캐릭터로 표현하기 위해 제작한 캐릭터 브랜딩 프로젝트입니다. 딸기를 모티브로 한 둥근 실루엣과 잎사귀, 작은 날개, 딸기 지팡이를 조합해 밝고 사랑스러운 인상의 캐릭터 홍베리를 디자인했습니다.\n\n기본 캐릭터를 중심으로 정면·측면·후면 턴어라운드와 다양한 표정 및 응용 동작을 제작해 캐릭터의 성격과 활용 범위를 확장했습니다. 또한 쇼핑백, 스티커, 패키지, 의류, 테이프, 그립톡 등 다양한 굿즈에 적용해 지역 특산물 캐릭터가 실제 브랜딩과 홍보 콘텐츠로 확장될 수 있는 가능성을 시각화했습니다.\n\n캐릭터와 그래픽 요소는 Adobe Illustrator를 중심으로 제작했으며, 이미지 보정과 합성 및 최종 시각화에는 Adobe Photoshop을 활용했습니다. 굿즈와 다양한 제품에 캐릭터가 적용된 모습을 구현하는 과정에는 Nano Banana Pro를 사용했습니다. 본 작품은 홍성 특산물 캐릭터 공모전 참가작으로 제작되었습니다.",
    descriptionEn: "‘Strawberry Fairy’ Hong Berry is a character branding project created for a Hongseong local specialty character competition. Inspired by the form and imagery of a strawberry, the character features a rounded silhouette, leafy details, small wings, and a strawberry wand to create a cheerful and approachable identity.\n\nThe project includes a full character turnaround, a range of facial expressions and poses, and various merchandise applications that expand Hong Berry into a broader visual system. The character was applied to shopping bags, stickers, packaging, apparel, tape, and grip accessories to explore its potential as a recognizable character for local branding and promotional use.\n\nAdobe Illustrator was used for the main character and graphic design, Adobe Photoshop for image editing, compositing, and final visual refinement, and Nano Banana Pro for visualizing the character across different product and merchandise applications. This project was created as an entry for the Hongseong Local Specialty Character Competition.",
    description: "A strawberry-inspired character branding project developed across character design, expressions, poses and merchandise applications.",
    video: null
  },
  {
    id: "coyseio-ai-fashion-film",
    title: "COYSEIO 재해석 AI 패션 콘셉트 필름",
    subtitle: "COYSEIO Reinterpretation — AI Fashion Concept Film",
    year: "2026",
    date: "2026.7.12",
    tools: ["GPT 2.0", "Kling AI"],
    bgm: "REMEDIOS — Paradise",
    category: "AI Fashion Film / Concept Direction",
    cover: "images/project03/cover.jpg?v=2",
    coverAlt: "숲속 소녀와 오두막을 담은 COYSEIO AI 패션 콘셉트 필름 썸네일",
    images: [],
    descriptionKo: "COYSEIO의 2026 S/S 컬렉션을 재해석한 AI 패션 콘셉트 필름입니다. 기존 코이세이오가 보여주던 일본 학생 교복을 연상시키는 단정하고 소녀적인 이미지에서 출발해, 이번 시즌에 두드러진 숲속 소녀 같은 자연스럽고 몽환적인 분위기를 하나의 짧은 서사로 연결했습니다.\n\n영상은 일본 학생을 연상시키는 한 소녀가 숲속을 걷다가 작은 개미를 발견하는 장면에서 시작됩니다. 소녀는 개미를 따라 숲속 깊이 들어가고, 길 끝에서 작은 열쇠를 발견합니다. 열쇠를 주운 소녀가 숲속 오두막에 도착해 문을 열면, 그 안에서 COYSEIO의 2026 S/S 시즌 의상들을 마주하게 됩니다.\n\n기존 브랜드의 소녀적인 정체성에서 새로운 시즌의 자연적이고 동화적인 무드로 변화하는 과정을 ‘익숙한 학생의 이미지가 숲속 소녀의 세계로 이동하는 이야기’로 시각화했습니다. 패션 컬렉션의 분위기를 단순히 보여주는 데 그치지 않고, 브랜드 이미지의 변화를 판타지적인 스토리텔링으로 연결하는 데 중점을 두었습니다.\n\n장면의 콘셉트 기획과 이미지 제작에는 GPT 2.0을 활용했으며, 캐릭터의 움직임과 숲속 공간, 개미를 따라가는 장면과 오두막으로 이어지는 시네마틱 영상 구현에는 Kling AI를 사용했습니다. 배경음악으로는 REMEDIOS의 ‘Paradise’를 사용해 숲속을 탐험하는 소녀의 몽환적이고 서정적인 분위기를 더했습니다.",
    descriptionEn: "This project is an AI fashion concept film reinterpreting COYSEIO’s 2026 S/S Collection. It begins with the brand’s familiar youthful aesthetic, reminiscent of Japanese school uniforms, and gradually transitions into the softer, dreamlike, forest-inspired mood of the new season.\n\nThe film follows a schoolgirl-like character who discovers a small ant while walking through the woods. She follows it deeper into the forest and finds a mysterious key at the end of the trail. After picking it up, she arrives at a secluded cabin, where she discovers the garments from COYSEIO’s 2026 S/S Collection.\n\nThe project visualizes the transition from COYSEIO’s established girlish identity to the more natural and fairy-tale-like atmosphere of the new collection. Rather than simply presenting the garments, the film uses a short fantasy narrative to connect fashion, seasonal identity, and cinematic storytelling.\n\nGPT 2.0 was used for concept development and visual generation, while Kling AI was used to create character movement, forest environments, and cinematic sequences. “Paradise” by REMEDIOS was used as the background music to reinforce the film’s dreamy and lyrical atmosphere.",
    description: "An AI fashion concept film reinterpreting COYSEIO’s 2026 S/S Collection through a short fantasy narrative.",
    video: "videos/project03-480.m4v"
  }
];
